#!/bin/sh
#
#############################################################
# Set up environment for GDAS Conventional Monitor job
########################################

#
# Specify whether the run is production or development
#
export envir=${envir:-prod}

echo `date` $0 `date -u` begin


########################################################### 
# set up working directory space
###########################################################
export CONMON_WORK_DIR=${CONMON_WORK_DIR:-/tmpnwprd}
export C_DATAROOT=${C_DATAROOT:-${CONMON_WORK_DIR}}

job=${job:-gdas_atmos_conmon}
pid=${pid:-$$}
export C_DATA=${C_DATA:-${C_DATAROOT}/${job}.${pid}}

if [[ -e ${C_DATA} ]]; then
   rm -rf ${C_DATA}
fi
mkdir -p ${C_DATA}
cd ${C_DATA}

###############################
# Specify NET and RUN name
##############################
export NET=${NET:-gfs}
export RUN=${RUN:-gdas}
export component=${component:-atmos}

export VERBOSE=${VERBOSE:-NO}
export HOMEgfs_conmon=${HOMEgfs_conmon:-${NWROOT}/gfs.${gfs_ver}}

export FIXgdas=${FIXgdas:-${HOMEgfs_conmon}/fix}
export PARMmon=${PARMmon:-${HOMEgfs_conmon}/parm/mon}

export HOMEconmon=${HOMEconmon:-${HOMEgfs_conmon}}
export EXECconmon=${EXECconmon:-${HOMEconmon}/exec}

export FIXconmon=${FIXconmon:-${FIXgfs}}
export USHconmon=${USHconmon:-${HOMEconmon}/ush}

export LITTLE_ENDIAN=${LITTLE_ENDIAN:-0}
export COMPRESS=${COMPRESS:-gzip}
export UNCOMPRESS=${UNCOMPRESS:-gunzip}
export Z=${Z:-gz}

export CLEAN_TANKDIR=${CLEAN_TANKDIR:-0}


##############################################################
# COMIN    - WHERE GSI OUTPUT (which is input data) RESIDES
# TANKDIR_cmon - WHERE OUTPUT DATA WILL RESIDE
##############################################################
export C_TANKDIR=${C_TANKDIR:-/com/verf/${envir}}
export C_COM_IN=${C_COM_IN:-${COMROOT}/${NET}/${envir}}

export C_COMIN=${C_COMIN:-$C_COM_IN/${RUN}.${PDY}}
export CONMON_SUFFIX=${CONMON_SUFFIX:-gdas}

m6h_date=`$NDATE -06 $PDATE`
export CYC_m6h=`echo $m6h_date|cut -c9-10`
export PDY_m6h=`echo $m6h_date|cut -c1-8`

export C_COMIN_m6h=${C_COMIN_m6h:-$C_COM_IN/${RUN}.${PDY_m6h}}

export CONMON_AREA=${CONMON_AREA:-glb}
export SAVE_WORK=${SAVE_WORK:-NO}


########################################################
# Execute the script.
${CONMONSH:-$HOMEgdas_conmon/scripts/exgdas_atmos_conmon.sh} ${PDY} ${CYC}
########################################################

date

